# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"

reviews:
  profile: "chill"
  high_level_summary: true
  poem: false
  review_status: true
  request_changes_workflow: false

  auto_review:
    enabled: true
    drafts: false

chat:
  auto_reply: false

# @coderabbitai review           → do a full fresh review right now
# @coderabbitai review this file → only review the file I'm pointing at
# @coderabbitai incremental      → review only the latest commits/changes
# @coderabbitai summarize        → just update/create the high-level summary
# @coderabbitai explain: line 42 → explain this piece of code