export const META = {
	//* author
	AUTHOR: "Hüsam 🥑 <devhsmq@gmail.com>",
	AUTHOR_NAME: "Hüsam",
	AUTHOR_AVATAR: "/avocado.png",
	AUTHOR_USERNAME: "husamql3",
	AUTHOR_GITHUB_LINK: "https://github.com/husamql3",
	//* site
	SITE_DESCRIPTION: "The modern pgAdmin alternative that works with every database.",
	SITE_KEYWORDS: [
		"pgadmin alternative",
		"database client",
		"database gui",
		"database browser",
		"sql editor",
		"postgresql client",
		"mysql client",
		"table editor",
		"ai sql",
		"er diagram",
	],
	SITE_TITLE: "DB Studio",
	SITE_NAME: "dbstudio.sh",
	SITE_URL: "https://dbstudio.sh",
	SITE_X_LINK: "https://x.com/dbstudio_sh",
	SITE_GITHUB_LINK: "https://github.com/husamql3/db-studio",
	SITE_GITHUB_NEW_ISSUE_LINK: "https://github.com/husamql3/db-studio/issues/new/choose",
	SITE_DOCS_LINK: "https://dbstudio.sh/docs",
	SITE_CHANGELOG_LINK: "https://dbstudio.sh/changelog",
	SITE_ROADMAP_LINK: "https://dbstudio.sh/roadmap",
	SITE_IMAGE: "https://dbstudio.sh/og-image.png",
	SITE_IMAGE_WIDTH: "1200",
	SITE_IMAGE_HEIGHT: "630",
	SITE_IMAGE_ALT: "dbstudio.sh – Modern database management studio",
	SITE_COLOR: "#1447e6",
};
