/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as PathlessLayoutIndexRouteImport } from './routes/_pathlessLayout/index'
import { Route as PathlessLayoutVisualizerRouteImport } from './routes/_pathlessLayout/visualizer'
import { Route as PathlessLayoutSchemaRouteImport } from './routes/_pathlessLayout/schema'
import { Route as PathlessLayoutLogsRouteImport } from './routes/_pathlessLayout/logs'
import { Route as PathlessLayoutIndexesRouteImport } from './routes/_pathlessLayout/indexes'
import { Route as PathlessLayoutTableIndexRouteImport } from './routes/_pathlessLayout/table/index'
import { Route as PathlessLayoutRunnerIndexRouteImport } from './routes/_pathlessLayout/runner/index'
import { Route as PathlessLayoutTableTableRouteImport } from './routes/_pathlessLayout/table/$table'
import { Route as PathlessLayoutRunnerQueryIdRouteImport } from './routes/_pathlessLayout/runner/$queryId'

const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutIndexRoute = PathlessLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutVisualizerRoute =
  PathlessLayoutVisualizerRouteImport.update({
    id: '/visualizer',
    path: '/visualizer',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutSchemaRoute = PathlessLayoutSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutLogsRoute = PathlessLayoutLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutIndexesRoute = PathlessLayoutIndexesRouteImport.update({
  id: '/indexes',
  path: '/indexes',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutTableIndexRoute =
  PathlessLayoutTableIndexRouteImport.update({
    id: '/table/',
    path: '/table/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutRunnerIndexRoute =
  PathlessLayoutRunnerIndexRouteImport.update({
    id: '/runner/',
    path: '/runner/',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutTableTableRoute =
  PathlessLayoutTableTableRouteImport.update({
    id: '/table/$table',
    path: '/table/$table',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutRunnerQueryIdRoute =
  PathlessLayoutRunnerQueryIdRouteImport.update({
    id: '/runner/$queryId',
    path: '/runner/$queryId',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/indexes': typeof PathlessLayoutIndexesRoute
  '/logs': typeof PathlessLayoutLogsRoute
  '/schema': typeof PathlessLayoutSchemaRoute
  '/visualizer': typeof PathlessLayoutVisualizerRoute
  '/': typeof PathlessLayoutIndexRoute
  '/runner/$queryId': typeof PathlessLayoutRunnerQueryIdRoute
  '/table/$table': typeof PathlessLayoutTableTableRoute
  '/runner': typeof PathlessLayoutRunnerIndexRoute
  '/table': typeof PathlessLayoutTableIndexRoute
}
export interface FileRoutesByTo {
  '/indexes': typeof PathlessLayoutIndexesRoute
  '/logs': typeof PathlessLayoutLogsRoute
  '/schema': typeof PathlessLayoutSchemaRoute
  '/visualizer': typeof PathlessLayoutVisualizerRoute
  '/': typeof PathlessLayoutIndexRoute
  '/runner/$queryId': typeof PathlessLayoutRunnerQueryIdRoute
  '/table/$table': typeof PathlessLayoutTableTableRoute
  '/runner': typeof PathlessLayoutRunnerIndexRoute
  '/table': typeof PathlessLayoutTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/_pathlessLayout/indexes': typeof PathlessLayoutIndexesRoute
  '/_pathlessLayout/logs': typeof PathlessLayoutLogsRoute
  '/_pathlessLayout/schema': typeof PathlessLayoutSchemaRoute
  '/_pathlessLayout/visualizer': typeof PathlessLayoutVisualizerRoute
  '/_pathlessLayout/': typeof PathlessLayoutIndexRoute
  '/_pathlessLayout/runner/$queryId': typeof PathlessLayoutRunnerQueryIdRoute
  '/_pathlessLayout/table/$table': typeof PathlessLayoutTableTableRoute
  '/_pathlessLayout/runner/': typeof PathlessLayoutRunnerIndexRoute
  '/_pathlessLayout/table/': typeof PathlessLayoutTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/indexes'
    | '/logs'
    | '/schema'
    | '/visualizer'
    | '/'
    | '/runner/$queryId'
    | '/table/$table'
    | '/runner'
    | '/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/indexes'
    | '/logs'
    | '/schema'
    | '/visualizer'
    | '/'
    | '/runner/$queryId'
    | '/table/$table'
    | '/runner'
    | '/table'
  id:
    | '__root__'
    | '/_pathlessLayout'
    | '/_pathlessLayout/indexes'
    | '/_pathlessLayout/logs'
    | '/_pathlessLayout/schema'
    | '/_pathlessLayout/visualizer'
    | '/_pathlessLayout/'
    | '/_pathlessLayout/runner/$queryId'
    | '/_pathlessLayout/table/$table'
    | '/_pathlessLayout/runner/'
    | '/_pathlessLayout/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/': {
      id: '/_pathlessLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/visualizer': {
      id: '/_pathlessLayout/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof PathlessLayoutVisualizerRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/schema': {
      id: '/_pathlessLayout/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof PathlessLayoutSchemaRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/logs': {
      id: '/_pathlessLayout/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof PathlessLayoutLogsRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/indexes': {
      id: '/_pathlessLayout/indexes'
      path: '/indexes'
      fullPath: '/indexes'
      preLoaderRoute: typeof PathlessLayoutIndexesRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/table/': {
      id: '/_pathlessLayout/table/'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof PathlessLayoutTableIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/runner/': {
      id: '/_pathlessLayout/runner/'
      path: '/runner'
      fullPath: '/runner'
      preLoaderRoute: typeof PathlessLayoutRunnerIndexRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/table/$table': {
      id: '/_pathlessLayout/table/$table'
      path: '/table/$table'
      fullPath: '/table/$table'
      preLoaderRoute: typeof PathlessLayoutTableTableRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/runner/$queryId': {
      id: '/_pathlessLayout/runner/$queryId'
      path: '/runner/$queryId'
      fullPath: '/runner/$queryId'
      preLoaderRoute: typeof PathlessLayoutRunnerQueryIdRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutIndexesRoute: typeof PathlessLayoutIndexesRoute
  PathlessLayoutLogsRoute: typeof PathlessLayoutLogsRoute
  PathlessLayoutSchemaRoute: typeof PathlessLayoutSchemaRoute
  PathlessLayoutVisualizerRoute: typeof PathlessLayoutVisualizerRoute
  PathlessLayoutIndexRoute: typeof PathlessLayoutIndexRoute
  PathlessLayoutRunnerQueryIdRoute: typeof PathlessLayoutRunnerQueryIdRoute
  PathlessLayoutTableTableRoute: typeof PathlessLayoutTableTableRoute
  PathlessLayoutRunnerIndexRoute: typeof PathlessLayoutRunnerIndexRoute
  PathlessLayoutTableIndexRoute: typeof PathlessLayoutTableIndexRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutIndexesRoute: PathlessLayoutIndexesRoute,
  PathlessLayoutLogsRoute: PathlessLayoutLogsRoute,
  PathlessLayoutSchemaRoute: PathlessLayoutSchemaRoute,
  PathlessLayoutVisualizerRoute: PathlessLayoutVisualizerRoute,
  PathlessLayoutIndexRoute: PathlessLayoutIndexRoute,
  PathlessLayoutRunnerQueryIdRoute: PathlessLayoutRunnerQueryIdRoute,
  PathlessLayoutTableTableRoute: PathlessLayoutTableTableRoute,
  PathlessLayoutRunnerIndexRoute: PathlessLayoutRunnerIndexRoute,
  PathlessLayoutTableIndexRoute: PathlessLayoutTableIndexRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
