#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DB_USER="${DB_USER:-dbstudio}"
DB_PASSWORD="${DB_PASSWORD:-dbstudio}"
DB_SERVICE="${DB_SERVICE:-FREEPDB1}"
DB_PORT="${DB_PORT:-1521}"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_CONTAINER="${DB_CONTAINER:-db-studio-oracle}"
DB_IMAGE="${DB_IMAGE:-gvenzl/oracle-free:23-slim-faststart}"
READY_TIMEOUT="${READY_TIMEOUT:-300}"

DATABASE_URL="${DATABASE_URL:-oracle://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_SERVICE}}"

if ! command -v docker >/dev/null 2>&1; then
  echo "[init-db-oracle] docker is not installed or not in PATH"
  exit 1
fi

if ! command -v bun >/dev/null 2>&1; then
  echo "[init-db-oracle] bun is not installed or not in PATH"
  exit 1
fi

# A restarted container keeps its old logs, so only logs written after the
# (re)start count as the readiness signal.
LOGS_SINCE=""
if docker ps -a --format '{{.Names}}' | grep -q "^${DB_CONTAINER}$"; then
  if ! docker ps --format '{{.Names}}' | grep -q "^${DB_CONTAINER}$"; then
    echo "[init-db-oracle] starting existing container ${DB_CONTAINER}..."
    LOGS_SINCE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    docker start "${DB_CONTAINER}" >/dev/null
  fi
else
  echo "[init-db-oracle] creating oracle container ${DB_CONTAINER}..."
  LOGS_SINCE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  docker run -d \
    --name "${DB_CONTAINER}" \
    -e ORACLE_PASSWORD="${DB_PASSWORD}" \
    -e APP_USER="${DB_USER}" \
    -e APP_USER_PASSWORD="${DB_PASSWORD}" \
    -p "${DB_PORT}:1521" \
    "${DB_IMAGE}" >/dev/null
fi

echo "[init-db-oracle] waiting for oracle to report ready (up to ${READY_TIMEOUT}s)..."
waited=0
until docker logs ${LOGS_SINCE:+--since "${LOGS_SINCE}"} "${DB_CONTAINER}" 2>&1 | grep -q "DATABASE IS READY TO USE"; do
  if ! docker ps --format '{{.Names}}' | grep -q "^${DB_CONTAINER}$"; then
    echo "[init-db-oracle] container ${DB_CONTAINER} exited; see: docker logs ${DB_CONTAINER}"
    exit 1
  fi
  if (( waited >= READY_TIMEOUT )); then
    echo "[init-db-oracle] timed out waiting for oracle; see: docker logs ${DB_CONTAINER}"
    exit 1
  fi
  sleep 2
  waited=$((waited + 2))
done

echo "[init-db-oracle] applying schema..."

# Runs from packages/server so oracledb (Thin mode, no Instant Client) resolves.
SEED_SCRIPT=$(cat <<'JS'
import oracledb from "oracledb";

const statements = [
  `DROP TABLE IF EXISTS projects`,
  `DROP TABLE IF EXISTS contributors`,
  `CREATE TABLE contributors (
    id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(255) NOT NULL,
    email      VARCHAR2(255) UNIQUE,
    is_active  BOOLEAN DEFAULT TRUE NOT NULL,
    birth_date DATE,
    profile    JSON,
    joined_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE projects (
    id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR2(255) NOT NULL UNIQUE,
    status   VARCHAR2(20) DEFAULT 'active' NOT NULL CHECK (status IN ('planning', 'active', 'archived')),
    budget   NUMBER(10, 2) DEFAULT 0 NOT NULL,
    owner_id NUMBER(10),
    CONSTRAINT fk_project_owner FOREIGN KEY (owner_id) REFERENCES contributors(id) ON DELETE SET NULL
  )`,
  `CREATE INDEX projects_owner_id_idx ON projects (owner_id)`,
  `INSERT INTO contributors (name, email, is_active, birth_date, profile, joined_at) VALUES
    ('Mona Patel', 'mona@example.com', TRUE, DATE '1994-04-19', '{"team": "core"}', TIMESTAMP '2024-01-15 09:00:00'),
    ('Diego Rivera', 'diego@example.com', FALSE, DATE '1991-11-03', NULL, TIMESTAMP '2023-10-21 14:30:00')`,
  `INSERT INTO projects (name, status, budget, owner_id) VALUES
    ('Nebula Analytics', 'active', 125000.50, (SELECT id FROM contributors WHERE email = 'mona@example.com')),
    ('Atlas Mobile', 'planning', 48000.00, (SELECT id FROM contributors WHERE email = 'diego@example.com'))`,
];

const connection = await oracledb.getConnection({
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  connectString: process.env.CONNECT_STRING,
});
try {
  for (const sql of statements) await connection.execute(sql);
  await connection.commit();
} finally {
  await connection.close();
}
JS
)

(cd "${ROOT_DIR}/packages/server" && \
  DB_USER="${DB_USER}" DB_PASSWORD="${DB_PASSWORD}" \
  CONNECT_STRING="${DB_HOST}:${DB_PORT}/${DB_SERVICE}" \
  bun -e "${SEED_SCRIPT}")

if [[ -f "${ROOT_DIR}/.env" ]]; then
  if grep -q '^DATABASE_URL=' "${ROOT_DIR}/.env"; then
    sed -i.bak "s#^DATABASE_URL=.*#DATABASE_URL=${DATABASE_URL}#g" "${ROOT_DIR}/.env"
    rm -f "${ROOT_DIR}/.env.bak"
  else
    echo "DATABASE_URL=${DATABASE_URL}" >> "${ROOT_DIR}/.env"
  fi
else
  echo "DATABASE_URL=${DATABASE_URL}" > "${ROOT_DIR}/.env"
fi

echo "[init-db-oracle] done. DATABASE_URL=${DATABASE_URL}"
